### ISSUE TITLE
Enhane UI of malaria app

### ISSUE THREAD

**Issue by r00pal** [systers/malaria-app-android#329]
## Description
Enhance overall UI of the app.
This issue fixes #307 
fixes #241 
fixes #215 
fixes #107 

### Update [Required]
- [ ] UI is changes as per discussion in the public channels

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
5 hours

**Comment by geekanamika** [comment]
UI was updated during GSoC period. 
For more changes, we can create separate issues instead, closing this issue.
